name: Test

on:
  workflow_dispatch:

jobs:
  testsolaris:
    runs-on: macos-latest
    name: Test a cf tunnel
    steps:
    - uses: actions/checkout@v4
    - name: Run establish a cf tunnel
      id: test
      uses: vmactions/cf-tunnel@main
      with:
        protocol: tcp
        port: 22
        
    - name: Keep runner alive for 4 hours
      run: |
        echo "Sleeping for 4 hours to keep session active..."
        Start-Sleep -Seconds 14400
